### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by GhaleonZ** [Lidocian/SingleCore_TC#3]
**Description**: The Lando Pet boxes you get at level 10 (assuming 20, 30, etc), do not have an icon in your inventory.

**Current behaviour**: Get the mail at level 10, the gift box has an icon in the mail, looting it and the pet boxes have icons in the loot window. They don't have icons in inventory.

**Expected behaviour**: Assuming they should have items

**Steps to reproduce the problem**:

1. Get a character to level 10.
2. Check your mail and get the gift box.
3. Loot it and view inventory.

**Branch(es)**: 335

**TC hash/commit**:  Version downloaded from the thread

**Operating system**:  Windows 7 Pro x64

**Comment by Lidocian** [comment]
sry if i dissapoint you **GhaleonZ** but i working just on the "**bot module**"
